# Generated by Django 6.0.7 on 2026-08-04 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='donor_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='نام کمک\u200cکننده'),
        ),
    ]
