services:
  - type: web
    name: my-django-shop
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn mysite.wsgi:application"
    envVars:
      - key: DJANGO_PRODUCTION
        value: "True"
