# Generated by Django 6.0.7 on 2026-07-29 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
