# Generated by Django 6.0.7 on 2026-07-29 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_advertisement_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
