# Generated by Django 6.0.7 on 2026-07-29 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_advertisement_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='duration',
            field=models.IntegerField(choices=[(7, '۷ روز'), (30, '۳۰ روز'), (90, '۹۰ روز')], default=30),
        ),
    ]
